### ISSUE TITLE
🐛 Bug Report: Error: Invalid URL

### ISSUE THREAD

**Issue by jack-theripper** [appwrite/sdk-for-cli#139]
### 👟 Reproduction steps

PS C:\Users\User> npm install -g appwrite-cli

added 118 packages in 2s

PS C:\Users\User> appwrite -v

6.0.0

PS C:\Users\User> appwrite login
? Enter your email abc@abc.com
? Enter your password ****
ℹ Info: For detailed error pass the --verbose or --report flag
✗ Error: Invalid URL

### 👍 Expected behavior

....

### 👎 Actual Behavior

PS C:\Users\User> appwrite login --verbose
? Enter your email abc@abc.com
? Enter your password ***************************
TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at Client.call (C:\Users\User\AppData\Roaming\npm\node_modules\appwrite-cli\lib\client.js:149:17)
    at accountCreateEmailPasswordSession (C:\Users\User\AppData\Roaming\npm\node_modules\appwrite-cli\lib\commands\account.js:1016:29)
    at loginCommand (C:\Users\User\AppData\Roaming\npm\node_modules\appwrite-cli\lib\commands\generic.js:57:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_URL',
  input: '/account/sessions/email'
}

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@jack-theripper, thanks for creating this issue! 🙏🏼 BTW, version 6.0.0 of the CLI is meant to be used with Appwrite 1.6, but Appwrite Cloud is currently on 1.5. As such, you might run into compatibility problems. It would be best to install version 5.0.5 instead.

Anyways, your endpoint might be wrong. What's the endpoint when you run `appwrite client --debug`? Since you're using Appwrite Cloud, it should be `https://cloud.appwrite.io/v1`.

**Comment by jack-theripper** [comment]
Endpoint is empty. I thought that the CLI should be immediately configured (npm install) for use with Appwrite Cloud. I understood the problem

Thanks for the reply. The issue can be closed

**Comment by stnguyen90** [comment]
Looks like `configEndpoint` ends up being an empty string here:

https://github.com/appwrite/sdk-for-cli/blob/aa696219ab06b8834d8a54c882050e23c2d62ba3/lib/commands/generic.js#L16

Because `globalConfig.getEndpoint()` returns an empty string which doesn't trigger the `??` to set it to the default value.
