### ISSUE TITLE
bug: using appwrite cli to update user prefs doesn't update them

### ISSUE THREAD

**Issue by dawid-niedzwiecki** [appwrite/sdk-for-cli#14]
I tried the following commands to update an existing users preferences:
```
root@expirapp:~# appwrite users updatePrefs --userId="613e723e32487" --prefs="{'wiek': 21}"
message : Invalid prefs: Value must be a valid object.
code : 400
version : 0.10.2
root@expirapp:~# appwrite users updatePrefs --userId="613e723e32487" --prefs="{'wiek': '21'}"
message : Invalid prefs: Value must be a valid object.
code : 400
version : 0.10.2
root@expirapp:~# appwrite users updatePrefs --userId="613e723e32487" --prefs="{"wiek": "21"}"
message : Invalid prefs: Value must be a valid object.
code : 400
version : 0.10.2
```
and many other combinations of ", ' and no quotations at all. It always gives me the same error (Value must be a valid object). When I use the CLI to create a user, it does create the user, but leaves the prefs untouched (meaning empty, no matter if I set them to something or not).

**Comment by stnguyen90** [comment]
I think this is happening because the prefs is a string and is never decoded to a PHP array so it gets sent to the server as a string rather than an object:

https://github.com/appwrite/sdk-for-cli/blob/master/app/users.php#L233

I will try to submit a PR but I'm not sure when I'll have time to do so.

**Comment by stnguyen90** [comment]
May I work on this issue for Hacktoberfest?
